
rules:
  - name: "Disallow console.log"
    paths: "**/*.js"
    severity: "error"
    instructions: "Avoid using console.log in production code. Use a proper logging library instead."

  - name: "Enforce Consistent Variable Naming"
    paths: "**/*.js"
    severity: "warning"
    instructions: "Ensure variable names are written in camelCase. Avoid using underscores or all uppercase for variable names."
